### ISSUE TITLE
lmdb parser can use an endianness switch

### ISSUE THREAD

**Issue by Artoria2e5** [catwell/cw-lua#2]
[lmdb uses big endian ints on BE machines](https://monero.stackexchange.com/a/4526), so something should be done on that. If all goes right it should be just a `>` or `<` thing for unpack.

**Comment by catwell** [comment]
That's very likely. I never used LMDB on a BE machine, nor do I have one.

I am not actively maintaining this code, it's more a toy than anything else (I used it to debug problems with LMDB databases, but I no longer use LMDB at work). If you submit a PR I can look at it / merge it though.

**Comment by catwell** [comment]
That's very likely. I never used LMDB on a BE machine, nor do I have one.

I am not actively maintaining this code, it's more a toy than anything else (I used it to debug problems with LMDB databases, but I no longer use LMDB at work). If you submit a PR I can look at it / merge it though.
