### ISSUE TITLE
SHA-256, Intel Core2Duo, XPSP3 x86, lua 5.1.5 + luajit 2.1 from Far 3.0.5843

### ISSUE THREAD

**Issue by z0hm** [catwell/cw-lua#3]
Command line Far:>lua:local sha=require'sha256' print(sha.hex("abc"))
result: 0000000000000000000000000000000000000000000000000000000000000000
this result returned for any input data, sha256.test.lua don't work.

This variant SHA-256 https://github.com/Egor-Skriptunoff/pure_lua_SHA work ok, like other SHA-256 algorithms.
lua:local sha=require'sha2' print(sha.sha256("abc"))
result: ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad

Is it possible to fix your sha256 code and make it as fast as possible for Far?

**Comment by catwell** [comment]
Until today I had never heard about Far (https://farmanager.com/).

If you like you can try to figure out what is wrong there, I probably won't have the time myself (I don't use LuaJIT anymore and I don't even use Windows much).

**Comment by z0hm** [comment]
Path from https://github.com/catwell/cw-lua/issues/1#issuecomment-414240595 work, but very slow - sha256 from sha2.lua by Egor-Skriptunoff about 8 times quckly (ffi luajit 2.1 x86).

**Comment by catwell** [comment]
Why do you want to use my version instead of his then?

**Comment by z0hm** [comment]
Yes, if it is faster

**Comment by z0hm** [comment]
Solution for luajit 2.1 x86:
  res[0], res[1], res[2], res[3] = res[0]+a+0LL, res[1]+b+0LL, res[2]+c+0LL, res[3]+d+0LL
  res[4], res[5], res[6], res[7] = res[4]+e+0LL, res[5]+f+0LL, res[6]+g+0LL, res[7]+h+0LL

**Comment by catwell** [comment]
@z0hm Great, you can submit that as a PR if you want it merged!
